export const routes = {
  login: '/login',
  dashboard: '/dashboard',
  agenda: '/agenda',
  empresas: '/empresas',
  usuarios: '/usuarios',
  propostas: '/propostas',
  documentos: '/documentos',
  reunioes: '/reunioes',
  relatorios: '/relatorios',
  notificacoes: '/notificacoes',
  pendingApproval: '/pending-approval',
  contratos: '/contratos',
  perfil: '/perfil',
} as const;
