spring.application.name=sistema_climbe
server.port=8080

cors.allowed-origins=http://localhost:5173,http://127.0.0.1:5173

jwt.secret=NDBONDYzNTI2NjU1NkE1ODZFMzI3MjM1NzUzODc4MkY0MTNGNDQyODQ3MkI0QjYyNTA2NDUzNjc1NjZCNTk3MA==
jwt.expiration-ms=1800000
jwt.refresh-expiration-ms=604800000

spring.security.oauth2.client.registration.google.client-id=local-client-id
spring.security.oauth2.client.registration.google.client-secret=local-client-secret
spring.security.oauth2.client.registration.google.scope=profile,email
